POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "node 12",
    "description": "Um video qualquer",
    "duration": 1234
}

###


GET http://localhost:3333/videos


###

PUT http://localhost:3333/videos/e9e0ab17-517b-4fbb-b6de-5a1a9b82fd7d
Content-Type: application/json

{
    "title": "oioiooi",
    "description": "Um video qualquer",
    "duration": 123
}

###

DELETE http://localhost:3333/videos/5918ff69-24cd-41cf-8179-408834dc00e5
Content-Type: application/json

{
    "title": "video2",
    "description": "Um video qualquer",
    "duration": 123
}
